version: '3.8'
services:
  jira:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/myplugin:latest
    ports:
      - "8080:8080"
    volumes:
      - jira_data:/var/atlassian/jira
    environment:
      - JVM_MINIMUM_MEMORY=256m     # Ultra conservative
      - JVM_MAXIMUM_MEMORY=768m     # Ultra conservative
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=jirapass
      - POSTGRES_DB=jiradb
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 128m              # Very small for PostgreSQL

volumes:
  jira_data:
  postgresql_data: